# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Starter pipeline
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $latestRelease = Invoke-WebRequest https://api.github.com/repos/Azure/azure-iotedge/releases/latest
      $json = $latestRelease.Content | ConvertFrom-Json
      write-host 'latest version:' $json.tag_name
      $url = $json.assets | ? { $_.Name -Match "iotedge_1.0.9-1_debian9_amd64.deb" }  | % browser_download_url
      write-host 'url:' $url
      Invoke-WebRequest -Uri $url -OutFile "$env:SYSTEM_ARTIFACTSDIRECTORY\iotedge_1.0.9-1_debian9_amd64.deb"

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**\*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Deployment'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureFileCopy@3
  displayName: 'AzureBlob File Copy'
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/_Drop_Deployment/drop'
    azureSubscription: AutomotiveEdge
    Destination: AzureBlob
    storage: automotiveedgestorage01
    ContainerName: iot