# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Starter pipeline
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $latestRelease = Invoke-WebRequest https://api.github.com/repos/Azure/azure-iotedge/releases/latest -Headers @{"Accept"="application/json"}
      $json = $latestRelease.Content | ConvertFrom-Json

      write-host 'latest version:' $json.tag_name
      $files = $json.assets | % browser_download_url

      $tempFiles = $files.split(" ")

      foreach ($url in $tempFiles) {
        try {
            Invoke-WebRequest -Uri $url -OutFile "$env:SYSTEM_ARTIFACTSDIRECTORY"
        } catch {
            throw "Unable to download '$($file.path)'"
        }
      }

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'